services:
  frontend:
    build:
      context: ./rendu/devweb
    container_name: techcorp-frontend
    ports:
      - "5173:5173"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: techcorp-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama_server:/ollama_server
    restart: always



volumes:
  ollama_data:
