services:
  frontend:
    build:
      context: ./rendu/devweb
    container_name: techcorp-frontend
    ports:
      - "5173:5173"
    depends_on:
      init-ollama:
        condition: service_completed_successfully
      ollama:
        condition: service_healthy

  ollama:
    image: ollama/ollama:latest
    container_name: techcorp-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama_server:/ollama_server
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "ollama list > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  init-ollama:
    image: ollama/ollama:latest
    container_name: techcorp-ollama-init
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama_server:/ollama_server
    environment:
      - OLLAMA_HOST=ollama:11434
    restart: on-failure
    entrypoint: ["/bin/sh"]
    command: ["-c", "ollama pull phi3.5 && ollama create phi3-financial -f /ollama_server/Modelfile"]

volumes:
  ollama_data:
