services:
  frontend:
    build:
      context: ./rendu/devweb
    container_name: techcorp-frontend
    ports:
      - "5173:5173"
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: techcorp-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama_server:/ollama_server
    restart: always

  init-ollama:
    image: ollama/ollama:latest
    container_name: techcorp-ollama-init
    depends_on:
      - ollama
    volumes:
      - ./ollama_server:/ollama_server
    environment:
      - OLLAMA_HOST=ollama:11434
    command: >
      sh -c "
      echo 'Patientez pendant que Ollama télécharge le modèle Phi-3.5...' &&
      sleep 5 &&
      ollama create phi3-financial -f /ollama_server/Modelfile &&
      echo 'Le modèle phi3-financial est prêt pour TechCorp !'
      "

volumes:
  ollama_data:
